-- One model's score on one metric of one snapshot.
CREATE TABLE IF NOT EXISTS lb_scores (
  id                      text PRIMARY KEY,
  snapshot_id             text NOT NULL REFERENCES lb_snapshots (id) ON DELETE CASCADE,
  model_id                text NOT NULL REFERENCES lb_models (id),
  configuration_key       text NOT NULL,
  configuration_label     text,
  configuration_kind      text,
  configuration_priority  integer,
  selected_for_product    boolean NOT NULL DEFAULT false,
  selection_reason        text,
  metric_key              text NOT NULL,
  metric_name             text,
  raw_score               double precision,
  normalized_score        double precision,
  lower_bound             double precision,
  upper_bound             double precision,
  source_rank             integer,
  sample_size             integer,
  source_model_name       text,
  source_organization     text,
  source_published_at     timestamptz,
  metadata                jsonb NOT NULL DEFAULT '{}',
  created_at              timestamptz NOT NULL DEFAULT now()
);
